[package]
name = "metadata-server"
version = "0.1.0"
edition = "2021"


[dependencies]
metadata-proto = { path = "../metadata-proto" }
metadata-logic = { path = "../metadata-logic" }
metadata-migration = { path = "../metadata-migration" }
actix-web = "4.2"
ethers = "2.0.0"
anyhow = "1.0"
async-trait = "0.1"
blockscout-display-bytes = "1.0"
blockscout-service-launcher = { version = "0.9.0", features = [ "database-0_12" ] }
config = "0.13"
sea-orm = "0.12.2"
serde = "1.0"
serde_json = "1.0.96"
tokio = { version = "1.23", features = [ "rt-multi-thread", "macros" ] }
tonic = "0.8"
thiserror = "1"
tracing = "0.1"


[dev-dependencies]
blockscout-service-launcher = { version = "*", features = [ "test-server", "test-database" ] }
pretty_assertions = "1.3"
reqwest = { version = "0.11", features = ["json"]}
